# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1440, 900)
        Form.setStyleSheet("")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 611, 831))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 609, 829))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(18)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(900, 380, 241, 71))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(920, 100, 501, 31))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background: rgba(0, 0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: black;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(920, 240, 501, 31))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background: rgba(0, 0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: black;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(1280, 10, 71, 51))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background: black;\n"
"color: #ffffff;\n"
"border-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Downloads/deletetrashbin_87227.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(1360, 10, 71, 51))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background: black;\n"
"color: #ffffff;\n"
"border-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"")
        self.pushButton_3.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(650, 390, 771, 491))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background: rgba(0, 0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: black;\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(640, 20, 271, 351))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 850, 611, 31))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background: black;\n"
"color: #ffffff;\n"
"border-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(920, 20, 113, 31))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background: black;\n"
"color: #ffffff;\n"
"border-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_2.raise_()
        self.scrollArea.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.pushButton_3.raise_()
        self.textEdit.raise_()
        self.pushButton_4.raise_()
        self.pushButton.raise_()
        self.pushButton_5.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p>No file selected</p></body></html>"))
        self.lineEdit.setText(_translate("Form", "Title:"))
        self.lineEdit_2.setText(_translate("Form", "Genre:"))
        self.pushButton_2.setText(_translate("Form", "Del"))
        self.pushButton_3.setText(_translate("Form", "Fav"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PT Mono\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\';\">Description:</span></p></body></html>"))
        self.pushButton_4.setText(_translate("Form", "Select file"))
        self.pushButton.setText(_translate("Form", "Новая заметка"))
        self.pushButton_5.setText(_translate("Form", "Exting"))
